-- PostgreSQL schema for the GenApp data access programs proven so far
-- (tests/local-runtime/examples/genapp_menu.cbl: Customer Inquire/Add/Update,
-- Motor Policy Add). Columns/types match the EXEC SQL statements in
-- base/src/lgacdb01.cbl, lgacdb02.cbl, lgapdb01.cbl exactly (column names,
-- at least - base/ never declares real Db2 DDL, this repo has no SQL source
-- of truth to copy from, so types are inferred from the COBOL host
-- variables' PICTUREs). Only the 4 tables the proven operations touch -
-- NOT the full 8-table schema the real app has (HOUSE, ENDOWMENT,
-- COMMERCIAL, CUSTOMER_SECURE's full use, CLAIM are still missing - add as
-- Step 5 reaches each one). See docs/local-cics-runtime-plan.md.
--
-- Applied automatically by setup-sql-bridge.ps1; safe to re-run (CREATE
-- TABLE IF NOT EXISTS - won't touch existing data).

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMERNUMBER   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRSTNAME        VARCHAR(10),
    LASTNAME         VARCHAR(20),
    DATEOFBIRTH      VARCHAR(10),
    HOUSENAME        VARCHAR(20),
    HOUSENUMBER      VARCHAR(4),
    POSTCODE         VARCHAR(8),
    PHONEMOBILE      VARCHAR(20),
    PHONEHOME        VARCHAR(20),
    EMAILADDRESS     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_SECURE (
    customerNumber   INTEGER PRIMARY KEY,
    customerPass     VARCHAR(32),
    state_indicator  CHAR(1),
    pass_changes     INTEGER
);

CREATE TABLE IF NOT EXISTS POLICY (
    POLICYNUMBER     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMERNUMBER   INTEGER,
    ISSUEDATE        VARCHAR(10),
    EXPIRYDATE       VARCHAR(10),
    POLICYTYPE       CHAR(1),
    LASTCHANGED      TIMESTAMP,
    BROKERID         INTEGER,
    BROKERSREFERENCE VARCHAR(10),
    PAYMENT          INTEGER
);

CREATE TABLE IF NOT EXISTS MOTOR (
    POLICYNUMBER       INTEGER PRIMARY KEY REFERENCES POLICY(POLICYNUMBER),
    MAKE               VARCHAR(15),
    MODEL              VARCHAR(15),
    VALUE              INTEGER,
    REGNUMBER          VARCHAR(7),
    COLOUR             VARCHAR(8),
    CC                 INTEGER,
    YEAROFMANUFACTURE  VARCHAR(10),
    PREMIUM            INTEGER,
    ACCIDENTS          INTEGER
);

-- Both IDENTITY sequences start well clear of base/data's seed VSAM records
-- (customers/policies 1-10 already exist in KSDSCUST.dat/KSDSPOLY.dat) so a
-- fresh Postgres insert doesn't collide with them on the VSAM side - see
-- docs/local-cics-runtime-plan.md, Step 4 point 4, for why that matters.
ALTER TABLE CUSTOMER ALTER COLUMN CUSTOMERNUMBER RESTART WITH 1000;
ALTER TABLE POLICY ALTER COLUMN POLICYNUMBER RESTART WITH 5000;
