-- PostgreSQL schema for the GenApp data access programs proven so far
-- (tests/local-runtime/examples/genapp_menu.cbl: Customer Inquire/Add/Update,
-- Motor and House Policy Add/Inquire/Delete/Update). Columns/types match the
-- EXEC SQL statements in base/src/lgacdb01.cbl, lgacdb02.cbl, lgapdb01.cbl,
-- lgipdb01.cbl, lgupdb01.cbl exactly (column names, at least - base/ never
-- declares real Db2 DDL, this repo has no SQL source of truth to copy from,
-- so types are inferred from the COBOL host variables' PICTUREs). Only the
-- tables the proven operations touch - NOT the full 8-table schema the real
-- app has (ENDOWMENT, COMMERCIAL, CUSTOMER_SECURE's full use, CLAIM are
-- still missing - add as Step 5 reaches each one). See
-- docs/local-cics-runtime-plan.md.
--
-- Applied automatically by setup-sql-bridge.ps1; safe to re-run (CREATE
-- TABLE IF NOT EXISTS - won't touch existing data).

CREATE TABLE IF NOT EXISTS CUSTOMER (
    CUSTOMERNUMBER   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRSTNAME        VARCHAR(10),
    LASTNAME         VARCHAR(20),
    DATEOFBIRTH      VARCHAR(10),
    HOUSENAME        VARCHAR(20),
    HOUSENUMBER      VARCHAR(4),
    POSTCODE         VARCHAR(8),
    PHONEMOBILE      VARCHAR(20),
    PHONEHOME        VARCHAR(20),
    EMAILADDRESS     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_SECURE (
    customerNumber   INTEGER PRIMARY KEY,
    customerPass     VARCHAR(32),
    state_indicator  CHAR(1),
    pass_changes     INTEGER
);

CREATE TABLE IF NOT EXISTS POLICY (
    POLICYNUMBER     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMERNUMBER   INTEGER,
    ISSUEDATE        VARCHAR(10),
    EXPIRYDATE       VARCHAR(10),
    POLICYTYPE       CHAR(1),
    LASTCHANGED      TIMESTAMP,
    BROKERID         INTEGER,
    BROKERSREFERENCE VARCHAR(10),
    PAYMENT          INTEGER
);

CREATE TABLE IF NOT EXISTS MOTOR (
    POLICYNUMBER       INTEGER PRIMARY KEY REFERENCES POLICY(POLICYNUMBER) ON DELETE CASCADE,
    MAKE               VARCHAR(15),
    MODEL              VARCHAR(15),
    VALUE              INTEGER,
    REGNUMBER          VARCHAR(7),
    COLOUR             VARCHAR(8),
    CC                 INTEGER,
    YEAROFMANUFACTURE  VARCHAR(10),
    PREMIUM            INTEGER,
    ACCIDENTS          INTEGER
);

CREATE TABLE IF NOT EXISTS HOUSE (
    POLICYNUMBER     INTEGER PRIMARY KEY REFERENCES POLICY(POLICYNUMBER) ON DELETE CASCADE,
    PROPERTYTYPE     VARCHAR(15),
    BEDROOMS         INTEGER,
    VALUE            INTEGER,
    HOUSENAME        VARCHAR(20),
    HOUSENUMBER      VARCHAR(4),
    POSTCODE         VARCHAR(8)
);

-- Both IDENTITY sequences start well clear of base/data's seed VSAM records
-- (customers/policies 1-10 already exist in KSDSCUST.dat/KSDSPOLY.dat) so a
-- fresh Postgres insert doesn't collide with them on the VSAM side - see
-- docs/local-cics-runtime-plan.md, Step 4 point 4, for why that matters.
--
-- setval(..., false), not RESTART WITH: this script re-runs every time
-- setup-sql-bridge.ps1 does, and RESTART WITH unconditionally rewinds the
-- sequence - on a DB that already has rows past the floor, the next INSERT
-- then collides with one of them ("duplicate key value violates unique
-- constraint policy_pkey"). setval(..., GREATEST(floor, max+1), false)
-- only ever moves the sequence forward.
SELECT setval(pg_get_serial_sequence('CUSTOMER', 'customernumber'),
              GREATEST(1000, (SELECT COALESCE(MAX(CUSTOMERNUMBER), 0) + 1 FROM CUSTOMER)),
              false);
SELECT setval(pg_get_serial_sequence('POLICY', 'policynumber'),
              GREATEST(5000, (SELECT COALESCE(MAX(POLICYNUMBER), 0) + 1 FROM POLICY)),
              false);

-- lgdpdb01.cbl (Delete Policy) only deletes FROM POLICY, relying - like the
-- real Db2 schema must - on the policy-type tables' FK having ON DELETE
-- CASCADE. The CREATE TABLE above already has it for fresh installs; this
-- ALTER fixes an already-existing MOTOR table from before this was added
-- (CREATE TABLE IF NOT EXISTS above won't retroactively change it).
ALTER TABLE MOTOR DROP CONSTRAINT IF EXISTS motor_policynumber_fkey;
ALTER TABLE MOTOR ADD CONSTRAINT motor_policynumber_fkey
    FOREIGN KEY (POLICYNUMBER) REFERENCES POLICY(POLICYNUMBER) ON DELETE CASCADE;
