// <auto-generated />
using System;
using GenApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenApp.Infrastructure.Migrations
{
    [DbContext(typeof(GenAppDbContext))]
    partial class GenAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenApp.Domain.Claims.Claim", b =>
                {
                    b.Property<int>("ClaimNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("claim_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClaimNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ClaimNumber"), 1000001L, null, null, null, null, null);

                    b.Property<string>("Cause")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cause");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<string>("Observations")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observations");

                    b.Property<int?>("Paid")
                        .HasColumnType("integer")
                        .HasColumnName("paid");

                    b.Property<int>("PolicyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("ClaimNumber")
                        .HasName("pk_claim");

                    b.HasIndex("PolicyNumber")
                        .HasDatabaseName("ix_claim_policy_number");

                    b.ToTable("claim", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("customer_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("CustomerNumber"), 1000001L, null, null, null, null, null);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("first_name");

                    b.Property<string>("HouseName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("house_name");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("house_number");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneHome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_home");

                    b.Property<string>("PhoneMobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_mobile");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode");

                    b.HasKey("CustomerNumber")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Customers.CustomerSecure", b =>
                {
                    b.Property<int>("CustomerNumber")
                        .HasColumnType("integer")
                        .HasColumnName("customer_number");

                    b.Property<string>("CustomerPass")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_pass");

                    b.Property<int?>("PassChanges")
                        .HasColumnType("integer")
                        .HasColumnName("pass_changes");

                    b.Property<string>("StateIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("state_indicator");

                    b.HasKey("CustomerNumber")
                        .HasName("pk_customer_secure");

                    b.ToTable("customer_secure", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Policies.CommercialPolicy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<short?>("CrimePeril")
                        .HasColumnType("smallint")
                        .HasColumnName("crime_peril");

                    b.Property<int?>("CrimePremium")
                        .HasColumnType("integer")
                        .HasColumnName("crime_premium");

                    b.Property<string>("Customer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("customer");

                    b.Property<short?>("FirePeril")
                        .HasColumnType("smallint")
                        .HasColumnName("fire_peril");

                    b.Property<int?>("FirePremium")
                        .HasColumnType("integer")
                        .HasColumnName("fire_premium");

                    b.Property<short?>("FloodPeril")
                        .HasColumnType("smallint")
                        .HasColumnName("flood_peril");

                    b.Property<int?>("FloodPremium")
                        .HasColumnType("integer")
                        .HasColumnName("flood_premium");

                    b.Property<string>("LatitudeN")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("latitude_n");

                    b.Property<string>("LongitudeW")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("longitude_w");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("property_type");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date")
                        .HasColumnName("renewal_date");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("request_date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short?>("WeatherPeril")
                        .HasColumnType("smallint")
                        .HasColumnName("weather_peril");

                    b.Property<int?>("WeatherPremium")
                        .HasColumnType("integer")
                        .HasColumnName("weather_premium");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("zipcode");

                    b.HasKey("PolicyNumber")
                        .HasName("pk_commercial");

                    b.ToTable("commercial", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Policies.EndowmentPolicy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    b.Property<string>("Equities")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("equities");

                    b.Property<string>("FundName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fund_name");

                    b.Property<string>("LifeAssured")
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("life_assured");

                    b.Property<string>("ManagedFund")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("managed_fund");

                    b.Property<string>("PaddingData")
                        .HasMaxLength(32606)
                        .HasColumnType("character varying(32606)")
                        .HasColumnName("padding_data");

                    b.Property<int?>("SumAssured")
                        .HasColumnType("integer")
                        .HasColumnName("sum_assured");

                    b.Property<short?>("Term")
                        .HasColumnType("smallint")
                        .HasColumnName("term");

                    b.Property<string>("WithProfits")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("with_profits");

                    b.HasKey("PolicyNumber")
                        .HasName("pk_endowment");

                    b.ToTable("endowment", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Policies.HousePolicy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    b.Property<short?>("Bedrooms")
                        .HasColumnType("smallint")
                        .HasColumnName("bedrooms");

                    b.Property<string>("HouseName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("house_name");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("house_number");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("property_type");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("PolicyNumber")
                        .HasName("pk_house");

                    b.ToTable("house", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Policies.MotorPolicy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    b.Property<int?>("Accidents")
                        .HasColumnType("integer")
                        .HasColumnName("accidents");

                    b.Property<short?>("Cc")
                        .HasColumnType("smallint")
                        .HasColumnName("cc");

                    b.Property<string>("Colour")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("colour");

                    b.Property<string>("Make")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("model");

                    b.Property<int?>("Premium")
                        .HasColumnType("integer")
                        .HasColumnName("premium");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("reg_number");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.Property<DateOnly?>("YearOfManufacture")
                        .HasColumnType("date")
                        .HasColumnName("year_of_manufacture");

                    b.HasKey("PolicyNumber")
                        .HasName("pk_motor");

                    b.ToTable("motor", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Policies.Policy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("policy_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PolicyNumber"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("PolicyNumber"), 1000001L, null, null, null, null, null);

                    b.Property<int?>("BrokerId")
                        .HasColumnType("integer")
                        .HasColumnName("broker_id");

                    b.Property<string>("BrokersReference")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("brokers_reference");

                    b.Property<short?>("Commission")
                        .HasColumnType("smallint")
                        .HasColumnName("commission");

                    b.Property<int>("CustomerNumber")
                        .HasColumnType("integer")
                        .HasColumnName("customer_number");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<DateTime>("LastChanged")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_changed")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Payment")
                        .HasColumnType("integer")
                        .HasColumnName("payment");

                    b.Property<string>("PolicyType")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("policy_type");

                    b.HasKey("PolicyNumber")
                        .HasName("pk_policy");

                    b.HasIndex("CustomerNumber")
                        .HasDatabaseName("ix_policy_customer_number");

                    b.ToTable("policy", (string)null);
                });

            modelBuilder.Entity("GenApp.Domain.Claims.Claim", b =>
                {
                    b.HasOne("GenApp.Domain.Policies.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_claim_policy_policy_number");
                });

            modelBuilder.Entity("GenApp.Domain.Customers.CustomerSecure", b =>
                {
                    b.HasOne("GenApp.Domain.Customers.Customer", null)
                        .WithOne()
                        .HasForeignKey("GenApp.Domain.Customers.CustomerSecure", "CustomerNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_secure_customer_customer_number");
                });

            modelBuilder.Entity("GenApp.Domain.Policies.CommercialPolicy", b =>
                {
                    b.HasOne("GenApp.Domain.Policies.Policy", null)
                        .WithOne()
                        .HasForeignKey("GenApp.Domain.Policies.CommercialPolicy", "PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commercial_policy_policy_number");
                });

            modelBuilder.Entity("GenApp.Domain.Policies.EndowmentPolicy", b =>
                {
                    b.HasOne("GenApp.Domain.Policies.Policy", null)
                        .WithOne()
                        .HasForeignKey("GenApp.Domain.Policies.EndowmentPolicy", "PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_endowment_policy_policy_number");
                });

            modelBuilder.Entity("GenApp.Domain.Policies.HousePolicy", b =>
                {
                    b.HasOne("GenApp.Domain.Policies.Policy", null)
                        .WithOne()
                        .HasForeignKey("GenApp.Domain.Policies.HousePolicy", "PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_house_policy_policy_number");
                });

            modelBuilder.Entity("GenApp.Domain.Policies.MotorPolicy", b =>
                {
                    b.HasOne("GenApp.Domain.Policies.Policy", null)
                        .WithOne()
                        .HasForeignKey("GenApp.Domain.Policies.MotorPolicy", "PolicyNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_motor_policy_policy_number");
                });

            modelBuilder.Entity("GenApp.Domain.Policies.Policy", b =>
                {
                    b.HasOne("GenApp.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policy_customer_customer_number");
                });
#pragma warning restore 612, 618
        }
    }
}
